// Database of "I love you" in 75+ languages of the world
const LOVE_LANGUAGES = [
    { lang: "Русский", text: "Я тебя люблю", native: "Я тебя люблю" },
    { lang: "English", text: "I love you", native: "I love you" },
    { lang: "Français", text: "Je t'aime", native: "Je t'aime" },
    { lang: "Español", text: "Te quiero", native: "Te quiero" },
    { lang: "Italiano", text: "Ti amo", native: "Ti amo" },
    { lang: "Deutsch", text: "Ich liebe dich", native: "Ich liebe dich" },
    { lang: "中文", text: "Wo ai ni", native: "我爱你" },
    { lang: "日本語", text: "Aishiteru", native: "愛してる" },
    { lang: "한국어", text: "Saranghae", native: "사랑해" },
    { lang: "العربية", text: "Uhibbuka", native: "أحبك" },
    { lang: "Português", text: "Eu te amo", native: "Eu te amo" },
    { lang: "Türkçe", text: "Seni seviyorum", native: "Seni seviyorum" },
    { lang: "हिन्दी", text: "Main tumse pyar karta hoon", native: "मैं तुमसे प्यार करता हूँ" },
    { lang: "Ελληνικά", text: "S'agapo", native: "Σ' αγαπώ" },
    { lang: "Nederlands", text: "Ik hou van jou", native: "Ik hou van jou" },
    { lang: "Svenska", text: "Jag älskar dig", native: "Jag älskar dig" },
    { lang: "Polski", text: "Kocham cię", native: "Kocham cię" },
    { lang: "Українська", text: "Я тебе кохаю", native: "Я тебе кохаю" },
    { lang: "Қазақша", text: "Men seni jaqsı köremin", native: "Мен сені жақсы көремін" },
    { lang: "O'zbek", text: "Men seni sevaman", native: "Men seni sevaman" },
    { lang: "Azərbaycan", text: "Mən səni sevirəm", native: "Mən səni sevirəm" },
    { lang: "Čeština", text: "Miluji tě", native: "Miluji tě" },
    { lang: "Magyar", text: "Szeretlek", native: "Szeretlek" },
    { lang: "Română", text: "Te iubesc", native: "Te iubesc" },
    { lang: "Tiếng Việt", text: "Anh yêu em", native: "Anh yêu em" },
    { lang: "ภาษาไทย", text: "Chan rak thoe", native: "ฉันรักเธอ" },
    { lang: "Bahasa Indonesia", text: "Aku cinta kamu", native: "Aku cinta kamu" },
    { lang: "עברית", text: "Ani ohev otach", native: "אני אוהב אותך" },
    { lang: "فارسی", text: "Dooset daram", native: "دوستت دارم" },
    { lang: "Norsk", text: "Jeg elsker deg", native: "Jeg elsker deg" },
    { lang: "Dansk", text: "Jeg elsker dig", native: "Jeg elsker dig" },
    { lang: "Suomi", text: "Minä rakastan sinua", native: "Minä rakastan sinua" },
    { lang: "Հայերեն", text: "Yes kez sirum em", native: "Ես քեզ sirum em" },
    { lang: "ქართული", text: "Mikvarxar", native: "მე შენ მიყვარხარ" },
    { lang: "Български", text: "Обичам те", native: "Обичам те" },
    { lang: "Hrvatski", text: "Volim te", native: "Volim te" },
    { lang: "Srpski", text: "Волим те", native: "Волим те" },
    { lang: "Slovenčina", text: "Ľúbim ťa", native: "Ľúbim ťa" },
    { lang: "Lietuvių", text: "Aš tave myliu", native: "Aš tave myliu" },
    { lang: "Latviešu", text: "Es tevi mīlu", native: "Es tevi mīlu" },
    { lang: "Eesti", text: "Ma armastan sind", native: "Ma armastan sind" },
    { lang: "Íslenska", text: "Ég elska þig", native: "Ég elska þig" },
    { lang: "Gaeilge", text: "Tá grá agam duit", native: "Tá grá agam duit" },
    { lang: "Català", text: "T'estimo", native: "T'estimo" },
    { lang: "Tagalog", text: "Mahal kita", native: "Mahal kita" },
    { lang: "Swahili", text: "Nakupenda", native: "Nakupenda" },
    { lang: "বাংলা", text: "Ami tomake bhalobashi", native: "আমি তোমাকে ভালোবাসি" },
    { lang: "मराठी", text: "Mi tujhyavar prem karto", native: "मी तुझ्यावर प्रेम करतो" },
    { lang: "தமிழ்", text: "Naan unnai kadhalikkiren", native: "நான் உன்னை காதலிக்கிறேன்" },
    { lang: "తెలుగు", text: "Nenu ninnu premistunnanu", native: "నేను నిన్ను ప్రేమిస్తున్నాను" },
    { lang: "മലയാളം", text: "Njan ninne premikkunnu", native: "ഞാൻ നിന്നെ സ്നേഹിക്കുന്നു" },
    { lang: "اردو", text: "Main tumse pyar karta hoon", native: "میں آپ سے محبت کرتا ہوں" },
    { lang: "Монгол", text: "Би чамд хайртай", native: "Би чамд хайртай" },
    { lang: "Esperanto", text: "Mi amas vin", native: "Mi amas vin" },
    { lang: "Latin", text: "Te amo", native: "Te amo" },
    { lang: "Тоҷикӣ", text: "Ман туро дӯст медорам", native: "Ман туро дӯст медорам" },
    { lang: "Кыргызча", text: "Мен сени сүйөм", native: "Мен сени сүйөм" },
    { lang: "Беларуская", text: "Я цябе кахаю", native: "Я цябе кахаю" },
    { lang: "Hawaiian", text: "Aloha au iā 'oe", native: "Aloha au iā 'oe" },
    { lang: "Amharic", text: "Iwedihalehu", native: "እወድሻለሁ" },
    { lang: "Nepali", text: "Ma timilai maya garchhu", native: "म तिमीलाई माया गर्छु" }
];

function getRandomLovePhrase() {
    return LOVE_LANGUAGES[Math.floor(Math.random() * LOVE_LANGUAGES.length)];
}
